#!/usr/bin/env bash
# This script installs nginx on ubuntu server

apt-get -y update
apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
ufw allow 'Nginx HTTP'
service nginx restart
